# Generated by Django 3.2.9 on 2021-11-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='max_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offers',
            name='min_salary',
            field=models.IntegerField(),
        ),
    ]
