# Generated by Django 3.2.9 on 2021-11-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0005_auto_20211125_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=100)),
                ('exp_lvl', models.CharField(choices=[('trainee', 'Stażysta'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('expert', 'Expert')], max_length=10)),
                ('skills', models.CharField(max_length=200)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_changes', to='data_scraper.offer')),
            ],
        ),
    ]
