# Generated by Django 3.2.9 on 2021-11-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=50)),
                ('offer_full_link', models.CharField(max_length=200)),
                ('position_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('min_salary', models.IntegerField(max_length=20)),
                ('max_salary', models.IntegerField(max_length=20)),
            ],
        ),
    ]
