# Generated by Django 3.2.9 on 2021-11-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0004_add_created_updated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='exp_lvl',
            field=models.CharField(choices=[('trainee', 'Stażysta'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('expert', 'Expert')], max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='from_site',
            field=models.CharField(choices=[('justjoin.it', 'justjoin.it'), ('nofluffjobs.com', 'NoFluffJobs')], max_length=20),
        ),
    ]
