# Generated by Django 3.2.9 on 2021-11-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0008_auto_20211129_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerskills',
            old_name='offer_id',
            new_name='offer',
        ),
    ]
